---
# playbook.yml
- name: "Provision Image"
  hosts: default
  become: true

  tasks:
    - name: Create Folders in Home Directory
      file:
        path: "/home/user1/folder1"
        state: directory
        owner: user1
        group: developers
        mode: "0755"

    - name: Create Folders in Home Directory
      file:
        path: "/home/user2/folder2"
        state: directory
        owner: user2
        group: developers
        mode: "0755"
