name: aws-ubuntu

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest" # or latest

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/builds/aws/."

      - name: Run `packer validate`
        id: validate
        run: packer validate ./packer/builds/aws/.

      - name: Run `packer build`
        id: build
        run: |
            export HCP_CLIENT_ID=${{ secrets.HCP_CLIENT_ID }}
            export HCP_CLIENT_SECRET=${{ secrets.HCP_CLIENT_SECRET }}

            packer build \
            -var 'run_id=${{ github.run_id }}}' \
            ./packer/builds/aws/.